from pathlib import Path
r=Path(r'D:\badizo-pos-main');s=r/'scripts/new-store-20260920'
p=s/'install-server.ps1';t=p.read_text();t=t.replace("    try {\n      $credentials=", "    $savedOutputEncoding=$OutputEncoding\n    try {\n      $OutputEncoding=[Text.UTF8Encoding]::new($false)\n      $credentials=");t=t.replace("      if($credentials){$credentials.password=''}","      $OutputEncoding=$savedOutputEncoding\n      if($credentials){$credentials.password=''}");p.write_text(t)
p=s/'create-guide.py';lines=p.read_text(encoding='utf8').splitlines()
edits={
"pair('This is one-click":("This setup supports an existing MySQL 8.0 Windows service on port 3306, Running and Automatic. It creates a separate empty store database; existing databases and root password are preserved.","MySQL 8.0 service port 3306లో Running, Automaticగా ఉంటే దానినే వాడుతుంది. కొత్త storeకి వేరే ఖాళీ database సృష్టిస్తుంది. పాత databases, root password మారవు."),
"pair('2. Wait while setup":("2. Existing MySQL: setup reuses its service (usually MySQL80), asks for the MySQL admin username and hidden password, then creates a separate database. With no MySQL service, setup installs bundled BadizoMySQL.","2. MySQL ఇప్పటికే ఉంటే అదే serviceను వాడి admin username, దాచిన password అడుగుతుంది. తర్వాత కొత్త database తయారు చేస్తుంది. MySQL లేకపోతే bundled BadizoMySQL install చేస్తుంది."),
"pair('3. Setup generates":("3. Enter the existing MySQL administrator password only in the local setup prompt, never in chat. Setup keeps that password unchanged and stores only the newly generated application DB login in NEW_STORE_CREDENTIALS.txt.","3. MySQL admin passwordను setupలో మాత్రమే ఇవ్వండి; chatలో పంపవద్దు. ఆ password మార్చదు. కొత్త application DB loginను NEW_STORE_CREDENTIALS.txtలో ఉంచుతుంది."),
"pair('3. Reboot the server":("3. Reboot the server. Confirm MySQL80 (existing setup) or BadizoMySQL (bundled setup) is Running/Automatic. Check Badizo POS Backend and Badizo Daily Local Backup tasks, then reconnect a client.","3. Restart తర్వాత MySQL80 లేదా BadizoMySQL service Running/Automaticగా ఉందో చూడండి. Backend, Daily Local Backup tasks తనిఖీ చేసి client మళ్లీ connect చేయండి.")
}
for i,line in enumerate(lines):
 for key,(en,te) in edits.items():
  if line.startswith(key):lines[i]='pair('+repr(en)+','+repr(te)+')'
p.write_text('\n'.join(lines),encoding='utf8')
p=s/'write-report.cjs';t=p.read_text();t=t.replace('Server setup refuses unrelated existing MySQL/POS installs and supports resuming its own incomplete install.','Server setup supports one existing MySQL 8.0 service Running/Automatic on 3306, or a bundled fresh service; existing POS installations are still not overwritten.')
t=t.replace('- Server creates a dedicated database user, random database passwords and JWT secret; secret files are Administrator/SYSTEM only.','- Existing MySQL mode creates a uniquely named empty badizo_new_* database and bz_* user; root password and unrelated databases remain unchanged. It prompts for admin credentials locally and does not persist that password. Installer ownership markers prevent adopting an unrelated database. Bundled fresh mode remains available. Secrets are Administrator/SYSTEM only.')
t=t.replace("'## Requested LAN / Excel / PRN changes'","'## Existing MySQL support','',\n'- Verified on isolated MySQL 8.0: separate database/user creation, retry preserving a sentinel table, ownership/password rejection, original database preserved and original root password still valid. No production database/service was changed.',\n'- Local read-only inspection found MySQL80 Running/Automatic and port 3306 listening. The installer also checks listener process ancestry against the selected service. Full elevated setup remains a new-PC acceptance check.','',\n'## Requested LAN / Excel / PRN changes'")
p.write_text(t)
