const fs=require('fs');
const f='backend/routes/auth.js';let s=fs.readFileSync(f,'utf8');s=s.replace('  return verifyLegacyDefaultPassword(user?.username, password);',"  return process.env.BADIZO_ALLOW_LEGACY_DEFAULT_PASSWORDS === 'true' && verifyLegacyDefaultPassword(user?.username, password);");fs.writeFileSync(f,s);
const q='scripts/new-store-20260920/qa-integration.cjs';s=fs.readFileSync(q,'utf8');
s=s.replace("Object.assign(process.env,{DB_HOST:","await control.query(\"CREATE USER 'badizo_app'@'localhost' IDENTIFIED BY ?\",[password]);\n await control.query(\"GRANT ALL PRIVILEGES ON badizo_release_qa.* TO 'badizo_app'@'localhost'\");\n Object.assign(process.env,{BADIZO_NEW_STORE:'true',MYSQLDUMP_PATH:path.join(release,'package/payload/mysql/bin/mysqldump.exe'),MYSQL_PATH:path.join(release,'package/payload/mysql/bin/mysql.exe'),DB_HOST:");s=s.replace("DB_USER:'root'","DB_USER:'badizo_app'");
s=s.replace("const token=tokens.server;",`const token=tokens.server;
 const [[blank]]=await db.query("SELECT setting_value FROM app_settings WHERE setting_key='bank_account_no'");assert.equal(blank.setting_value,'');
 results.push({check:'New-store bank/GST identity is cleared',status:'PASS'});
 const users=await request('/api/users',null,token), qaAdmin=users.find(u=>u.username==='admin2');
 await request('/api/users',{...qaAdmin,password:'QaChangedPassword123'},token);
 await request('/api/auth/login',{username:'admin2',password:'admin123'},null,401);
 await request('/api/auth/login',{username:'admin2',password:'QaChangedPassword123'},null);
`);
s=s.replace(" fs.writeFileSync(path.join(release,'qa/summary.json'),JSON.stringify({at:",` const backupService=require(path.join(backend,'services/backupService'));
 const backup=await backupService.runDatabaseBackup();
 assert.ok(fs.statSync(backup.path).size>1000);
 await backupService.restoreDatabaseBackup(backup.file);
 const [[restored]]=await db.query('SELECT COUNT(*) n FROM invoices');assert.equal(Number(restored.n),1);
 results.push({check:'mysqldump backup + restore with limited database user on isolated DB',status:'PASS'});
 fs.writeFileSync(path.join(release,'qa/summary.json'),JSON.stringify({at:`);
fs.writeFileSync(q,s);
