from pathlib import Path
r=Path(r'D:\badizo-pos-main');p=r/'scripts/new-store-20260920/create-guide.py'
lines=p.read_text().splitlines()
replacements={
"pair('2. Put all PCs":("2. Connect the shop LAN. Setup fixes the selected server adapter at 192.168.1.10 / 255.255.255.0. Exclude .10 from router DHCP. If multiple adapters are active, choose the shop LAN adapter.","2. Shop LAN కలపండి. Server adapterను setup 192.168.1.10 / 255.255.255.0కి మారుస్తుంది. Router DHCPలో .10 ఇవ్వకుండా ఉంచండి. Adapters ఎక్కువ ఉంటే shop LAN ఎంచుకోండి."),
"pair('2. Enter the NEW":("2. Clients automatically connect to 192.168.1.10:5000. Use any unique reachable LAN IP, normally 192.168.1.2-254 except .10. DHCP is fine. Another subnet needs LAN routing; internet is unnecessary.","2. Clients ఆటోమేటిక్‌గా 192.168.1.10:5000కి connect అవుతాయి. సాధారణంగా .10 తప్ప 192.168.1.2-254లో unique IP లేదా DHCP వాడండి. వేరే subnet అయితే LAN routing కావాలి; internet అవసరం లేదు."),
"pair('Bundled:":("Bundled: Node, MySQL, VC++ runtime and desktop app. Installation and local POS work over LAN without internet. Bring model-specific printer drivers on USB. Online messaging, cloud and external gateways stay unavailable offline.","Node, MySQL, VC++, POS app packageలో ఉన్నాయి. Install, local POSకి LAN చాలు. Printer model drivers USBలో తెచ్చుకోండి. Internet లేకుండా cloud/messages/external gateways పనిచేయవు."),
"pair('1. Local backup":("1. Windows task Badizo Daily Local Backup runs at 09:00 server local time. If powered off, it catches up after startup; sleep wake depends on Windows support. Confirm Windows time/timezone and keep the server available.","1. Badizo Daily Local Backup task server time ప్రకారం ఉదయం 9కి run అవుతుంది. PC ఆఫ్ అయితే startup తర్వాత backup అవుతుంది. Sleep wake Windowsపై ఆధారపడుతుంది. Time/timezone సరిచూడండి."),
"pair('2. In System > Backup":("2. Use 08_BACKUP_NOW.bat on the SERVER for a full local ZIP. Check C:\\BadizoPOS\\backups: database.sql, barcode templates, generated PRN output and thermal files are archived. Copy the ZIP to a separate disk.","2. SERVERలో 08_BACKUP_NOW.batతో పూర్తి ZIP తీసుకోండి. backups folderలో SQL, barcode templates/output PRN, thermal files ఉంటాయి. ZIPను వేరే diskకు copy చేయండి."),
"pair('4. Restore first":("4. Extract a backup ZIP to a separate folder; test database.sql restore only on an isolated installation. Restore barcode templates/output and thermal files separately as needed. A live restore needs current backup and closed sales.","4. ZIP extract చేసి database.sqlను ముందుగా test installationలో restore చేయండి. Barcode/thermal files అవసరమైతే వేరుగా restore చేయండి. Live restore ముందు backup తీసుకుని sales ఆపాలి."),
"pair('5. Google Drive":("5. Automatic backup writes last-local-backup.json only after ZIP verification. Failures go to backup-errors.log and Task Scheduler retries. The System > Backup button creates SQL only; use the supplied BAT for SQL + PRN.","5. ZIP check తర్వాతే last-local-backup.json రాస్తుంది. Fail అయితే backup-errors.log చూడండి; task retry చేస్తుంది. System > Backup SQL మాత్రమే; SQL + PRN కోసం ఇచ్చిన BAT వాడండి.")
}
for i,line in enumerate(lines):
 for key,(en,te) in replacements.items():
  if line.startswith(key):lines[i]='pair('+repr(en)+','+repr(te)+')'
t='\n'.join(lines)
t=t.replace('role/server selection','role selection').replace('Role, server పేరు, Windows','Role, LAN adapter, Windows')
t=t.replace("def footer(c,d):", """title(14,'New SKU Excel upload','Excel నుంచి కొత్త products నమోదు')
pair('1. Open NEW_SKU_UPLOAD.xlsx from this package. Keep Upload as the first sheet and keep row 1 unchanged. Fill your products from row 2; the template has no sample products on the upload sheet.','1. Packageలో NEW_SKU_UPLOAD.xlsx తెరవండి. Upload మొదటి sheetగా, row 1 headers అలాగే ఉంచండి. Row 2 నుంచి మీ products ఇవ్వండి. Uploadలో sample data లేదు.')
pair('2. Keep Product Code, Barcode and HSN as Text so leading zeros survive. Give unique codes and a description. Fill Unit, measure, prices, tax breakup and purchase-unit conversion; the Guide sheet explains every column.','2. Code, barcode, HSN Textగా ఉంచండి; ముందు సున్నాలు పోవద్దు. Unique codes, పేరు, unit, measure, ధరలు, tax, purchase conversion ఇవ్వండి. Guide sheetలో వివరాలు ఉన్నాయి.')
pair('3. Save as .xlsx. Sign in as Server/Admin, open Inventory and choose Excel/CSV import. Select the saved file and review the confirmation. Check Import History until Completed; inspect skipped/error rows.','3. .xlsxగా save చేయండి. Server/Adminతో Inventoryలో Excel/CSV import ఎంచుకోండి. File ఎంచుకుని confirmation చూసి import చేయండి. Import Historyలో complete అయ్యేవరకు చూసి errors సరిచూడండి.')
pair('4. Inward Quantity ADDS stock each time. Reimporting the same quantity adds it again. For price-only updates use 0. PRN generation also adds sticker-count stock: when labels provide opening stock, import 0 first.','4. Inward Quantity ప్రతిసారీ stockకు చేరుతుంది. అదే quantity మళ్లీ import చేస్తే మళ్లీ పెరుగుతుంది. Rate updateకి 0 ఇవ్వండి. PRNలో sticker count కూడా stockకు చేరుతుంది; labels ద్వారా opening stock వేస్తే Excelలో 0 ఇవ్వండి.')
pair('5. Start with two test SKUs. Verify codes, prices, tax and stock, generate one PRN, print/scan one label and verify stock again. Then import your full master once. Bundled PRN templates are in payload/app/barcode/templates.','5. మొదట రెండు test SKUs import చేసి code, rate, tax, stock చూడండి. ఒక PRN తయారు చేసి label print/scan చేసి stock మళ్లీ చూడండి. తర్వాత పూర్తి master ఒక్కసారి import చేయండి. PRN templates packageలో ఉన్నాయి.')

def footer(c,d):""")
p.write_text(t)
# preserve existing-store seed time; new-store override remains 09:00
p=r/'backend/config/db.js';t=p.read_text().replace("('backup_daily_time', '09:00')","('backup_daily_time', '22:30')",1);p.write_text(t)
