const fs=require('fs'),path=require('path'),cp=require('child_process');
const root=path.resolve(__dirname,'../..'),release=path.join(root,'output/new-store-20260920'),pkg=path.join(release,'package');
const qa=JSON.parse(fs.readFileSync(path.join(release,'qa/summary.json')));
const report=[
'# Badizo new-store release validation - 20 September 2026','',
'Prepared from the current working tree, including existing uncommitted books/ledger updates. Intended for NEW STORE installation only. No live database was copied, no live bill was created, and no physical print job was sent.','',
'## Results','',
'| Verification | Result |','|---|---|',
'| Backend regression suite | 32 passed |',
'| Frontend regression suite | 23 passed across 8 suites |',
'| Isolated real MySQL integration checks | '+qa.results.filter(x=>x.status==='PASS').length+' passed; 0 failed |',
'| Production frontend | Compiled successfully |',
'| Current Electron NSIS x64 installer | Built successfully |',
'| Installer PowerShell files | Syntax/parser checks passed |',
'| A4 short invoice | Native Electron PDF, 1 page; visually reviewed |',
'| A4 long invoice | Native Electron PDF, 2 pages; all 65 item codes present; visually reviewed |',
'| Thermal 80 mm | Native Electron PDF, 1 page; visually reviewed |',
'| Telugu-English guide | 14 pages, shaped Telugu text; rendered and visually reviewed |',
'| Microsoft VC++ redistributable | Authenticode status Valid, Microsoft Corporation |','',
'## Release fixes','',
'- Fresh store defaults clear the old shop GST/contact/bank identity once, while preserving subsequently saved new-store settings.',
'- Frontend loading defaults and empty A4 bank fallback no longer inject the old store identity/account.',
'- Added DB_PORT support for the connection pool and backup/restore clients.',
'- Windows task runs full local SQL + barcode templates/output PRN + thermal ZIP backup daily at 09:00, plus startup catch-up, duplicate suppression and failure retries. Backend timer is disabled to avoid two schedules. Actual future trigger/wake execution on a new PC remains a site acceptance check.',
'- Legacy hardcoded D-drive cloud catch-up is disabled for this new-store package; unconfigured cloud notifications are suppressed. Google Drive credentials are not bundled.',
'- Changed passwords no longer accept legacy default passwords unless an explicit compatibility environment flag is enabled. Old-password rejection and new-password login were tested.',
'- MySQL runtime and VC++ dependency are bundled. Server adapter is configured to 192.168.1.10/24. Clients have no per-IP allowlist and need reachable LAN connectivity; another subnet requires routing. Server setup supports one existing MySQL 8.0 service Running/Automatic on 3306, or a bundled fresh service; existing POS installations are still not overwritten.',
'- Existing MySQL mode creates a uniquely named empty badizo_new_* database and bz_* user; root password and unrelated databases remain unchanged. It prompts for admin credentials locally and does not persist that password. Installer ownership markers prevent adopting an unrelated database. Bundled fresh mode remains available. Secrets are Administrator/SYSTEM only.',
'- All role launchers use fixed 192.168.1.10 and checksum verification. Stale cache/common-name discovery is suppressed when discovery is disabled; a focused VM regression test passed. Windows UTF-8 BOM configuration is accepted. Payroll uses existing Admin access; it is not an employee-only security role.','',
'## Existing MySQL support','',
'- Verified on isolated MySQL 8.0: separate database/user creation, retry preserving a sentinel table, ownership/password rejection, original database preserved and original root password still valid. No production database/service was changed.',
'- Local read-only inspection found MySQL80 Running/Automatic and port 3306 listening. The installer also checks listener process ancestry against the selected service. Full elevated setup remains a new-PC acceptance check.','',
'## Requested LAN / Excel / PRN changes','',
'- Included a blank 21-column NEW_SKU_UPLOAD.xlsx, with text code/barcode/HSN columns, unit validation and Telugu-English Guide sheet. Imported two isolated test SKUs through the actual frontend converter and backend API; leading zeros, price and stock were verified.',
'- Tested full backup ZIP contents, same-day duplicate suppression and failure handling on an isolated root/database. Error exit and preservation of the last successful archive marker passed.',
'- New-store application time setting is 09:00. Scheduled backup uses server Windows local time. If the PC is off, backup occurs after next startup; wake support is OS/hardware dependent.',
'- No external font/CDN references found in frontend source/public assets. Required application runtimes are bundled; printer drivers must be supplied for the actual models. Online integrations are not part of offline operation.','',
'## Scope and remaining acceptance','',
'Not performed: installation on a separate clean Windows machine/VM; Windows service registration/UAC/NSIS on that target; target reboot recovery; physical static-IP change/conflict detection; actual 09:00 Windows trigger/wake; real LAN clients; actual USB/network thermal, barcode or A4 printing; printer driver installation/calibration; every business combination and report UI variant; external Google Drive/SMS/WhatsApp/GST gateway activation. These require the new-store commissioning checklist in the PDF.',
'Software tests do not certify all devices or all workflows. The guide supplies explicit short/long print, barcode scan, first-sale, reconciliation and backup/restore steps.',
'Barcode behavior: /api/barcode/prn increases stock by the requested sticker count and writes a stock adjustment. A generated PRN is not a stock-neutral reprint. Four templates were tested without spooling physical labels.',
'Build advisory: frontend bundle size is larger than the tool recommendation. Jest PDF-import tests log missing canvas polyfill warnings in Node; tests passed, and native Electron PDF output was separately checked.',
'The existing application has static/default terms and seed settings. New-store initialization clears the store-specific seed identity; enter and verify the new shop identity and receipt terms before trading.',
'Database backup/restore was tested only on the isolated localhost:33360 database using a schema-limited user. No production restore was attempted.','',
'## Individual integration checks','',
'| Check | Result |','|---|---|',
...qa.results.map(r=>'| '+r.check.replace(/\|/g,'/')+' | '+r.status+' |'),
'','## Primary runtime references','',
'- MySQL initialization/service configuration: https://dev.mysql.com/doc/mysql-installation-excerpt/8.0/en/data-directory-initialization.html',
'- Microsoft VC++ runtime: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist',
'','Included MySQL license is under payload/mysql/LICENSE; Electron and its third-party notices are inside the installed desktop runtime.',''
];
fs.writeFileSync(path.join(pkg,'VALIDATION_REPORT.md'),report.join('\n'));
fs.writeFileSync(path.join(pkg,'SOFTWARE_TEST_RESULTS.json'),JSON.stringify(qa,null,2));
console.log('Validation report written.');
